[custom]
ruleset=🎯 BYR代理,https://raw.githubusercontent.com/metawarma/ACL4SSR/master/Clash/Ruleset/byr.list
ruleset=🚀 dota2server,https://raw.githubusercontent.com/metawarma/ACL4SSR/refs/heads/master/Clash/Ruleset/Dota2.list
ruleset=🚀 Steam国际,https://raw.githubusercontent.com/metawarma/ACL4SSR/refs/heads/master/Clash/Ruleset/steamdota2
ruleset=🚀 节点选择,rules/ACL4SSR/Clash/Telegram.list
ruleset=🚀 节点选择,rules/ACL4SSR/Clash/ProxyMedia.list
ruleset=🚀 节点选择,rules/ACL4SSR/Clash/ProxyLite.list
ruleset=🚀 节点选择,DOMAIN-KEYWORD,leetcode
ruleset=🚀 Steam国际,rules/ACL4SSR/Clash/Ruleset/Steam.list
ruleset=🚀 Steam国服,rules/ACL4SSR/Clash/Ruleset/SteamCN.list
ruleset=🎯 全球直连,rules/ACL4SSR/Clash/LocalAreaNetwork.list
ruleset=🛑 全球拦截,rules/ACL4SSR/Clash/BanAD.list
ruleset=🛑 全球拦截,rules/ACL4SSR/Clash/BanProgramAD.list
ruleset=🎯 全球直连,rules/ACL4SSR/Clash/GoogleCN.list
ruleset=🎯 全球直连,rules/ACL4SSR/Clash/ChinaDomain.list
ruleset=🎯 全球直连,rules/ACL4SSR/Clash/ChinaCompanyIp.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL


custom_proxy_group=🚀 节点选择`select`[]🔯 故障转移`[]🔮 负载均衡`[]DIRECT`[]🚀 手动切换
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=🚀 dota2server`select`[]🔯 故障转移`[]DIRECT`[]🚀 手动切换`.*
custom_proxy_group=🚀 Steam国际`select`[]🔯 故障转移`[]🔮 负载均衡`[]DIRECT`[]🚀 手动切换`.*
custom_proxy_group=🚀 Steam国服`select`[]🔯 故障转移`[]🔮 负载均衡`[]DIRECT`[]🚀 手动切换`.*
custom_proxy_group=🎯 BYR代理`select`[]🔯 故障转移`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`^(?=.*(港|新|美)).*(10x|5x).*$`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🔯 故障转移`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🔮 负载均衡`load-balance`^(?!.*(10x|5x|4x)).*(港|新|日).*$`http://cp.cloudflare.com/generate_204`30
custom_proxy_group=🔯 故障转移`select`[]🔯 故障转移港新日`[]🔯 故障转移港`[]🔯 故障转移新
custom_proxy_group=🔯 故障转移港新日`fallback`^(?!.*(10x|5x|4x)).*(港|新|日).*$`http://cp.cloudflare.com/generate_204`30
custom_proxy_group=🔯 故障转移港`fallback`^(?!.*(10x|5x|4x)).*(港).*$`http://cp.cloudflare.com/generate_204`30
custom_proxy_group=🔯 故障转移新`fallback`^(?!.*(10x|5x|4x)).*(新).*$`http://cp.cloudflare.com/generate_204`30
enable_rule_generator=true
overwrite_original_rules=true
